import { buildSimulationConfig } from "./config.js";
import { forceToConfig } from "./forces.js";
import { RADIUS } from "./cell-model.js";
import { runtimeSettings } from "./runtime.js";

const ZLO = -0.25;
const ZHI = 0.25;
const PI = "3.141592653589793";
const PARTICLE_DIAMETER = 2 * RADIUS;
const PARTICLE_DENSITY = 1.0;
export function buildRunFiles(state, cell) {
  const config = buildSimulationConfig(state, cell);
  return [
    {
      filename: "simulation.json",
      mimeType: "application/json",
      content: JSON.stringify(config, null, 2) + "\n",
    },
    {
      filename: "particles.data",
      mimeType: "text/plain",
      content: generateParticlesData(state, cell),
    },
    {
      filename: "in.confined_spheres.lammps",
      mimeType: "text/plain",
      content: generateLammpsInput(state, cell),
    },
    {
      filename: "README.txt",
      mimeType: "text/plain",
      content: generateReadme(state, cell),
    },
  ];
}

export function downloadTextFile(file) {
  const blob = new Blob([file.content], { type: file.mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = file.filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

export function activeParticles(state, cell) {
  return cell.particles.filter((particle) => !state.disabledParticleIds.has(particle.id));
}

export function generateParticlesData(state, cell) {
  const particles = activeParticles(state, cell);
  const domain = lammpsDomainExtents(cell);
  const lines = [
    "LAMMPS data file: confined-spheres UI export",
    "",
    `${particles.length} atoms`,
    "1 atom types",
    "",
    `${fmt(domain.xlo)} ${fmt(domain.xhi)} xlo xhi`,
    `${fmt(domain.ylo)} ${fmt(domain.yhi)} ylo yhi`,
    `${fmt(ZLO)} ${fmt(ZHI)} zlo zhi`,
    "",
    "Atoms # sphere",
    "",
  ];

  particles.forEach((particle, index) => {
    lines.push(`${index + 1} 1 ${fmt(PARTICLE_DIAMETER)} ${fmt(PARTICLE_DENSITY)} ${fmt(particle.x)} ${fmt(particle.y)} 0.0`);
  });

  return lines.join("\n") + "\n";
}

export function generateLammpsInput(state, cell) {
  const forceVariables = generateForceVariables(state);
  const wallLines = generateConfinementWall(state, cell);
  const runtime = runtimeSettings(state);
  const notes = [
    "# Generated by confined-spheres UI.",
    `# Physical confinement shape: ${cell.confinementShape}.`,
    "# The rectangular simulation box only provides the LAMMPS domain.",
    `# Runtime: timestep ${runtime.timestep}, run ${runtime.runSteps}, simulated time ${runtime.timestep * runtime.runSteps}.`,
    `# Output: dump every ${runtime.dumpEvery} steps, thermo every ${runtime.thermoEvery} steps.`,
  ];
  const lines = [
    ...notes,
    "",
    "units lj",
    "atom_style sphere",
    "atom_modify map array",
    "dimension 2",
    "boundary f f p",
    "newton on",
    "comm_modify vel yes",
    "",
    "read_data particles.data",
    "",
    "variable kn equal 100000.0",
    "variable gamman equal 50.0",
    "pair_style gran/hooke/history ${kn} NULL ${gamman} NULL 0.0 1",
    "pair_coeff * *",
    "",
    "neighbor 0.3 bin",
    "neigh_modify every 1 delay 0 check yes",
    "",
    `timestep ${fmt(runtime.timestep)}`,
    "velocity all create 0.0 12345 mom yes rot no dist gaussian",
    "",
    "fix keep2d all enforce2d",
    "fix integrate all nve/sphere disc",
    ...wallLines,
    "",
    ...forceVariables,
    "fix drive all addforce v_fdrive_x v_fdrive_y 0.0",
    "",
    `thermo ${runtime.thermoEvery}`,
    "thermo_style custom step atoms temp pe ke etotal",
    `dump traj all custom ${runtime.dumpEvery} dump.confined_spheres.lammpstrj id type radius x y z vx vy vz`,
    "",
    `run ${runtime.runSteps}`,
    "",
  ];

  return lines.join("\n");
}

export function generateReadme(state, cell) {
  const activeCount = activeParticles(state, cell).length;
  const runtime = runtimeSettings(state);
  return [
    "Confined spheres UI export",
    "",
    "Files:",
    "- simulation.json: source configuration exported by the browser UI",
    "- particles.data: active particles in LAMMPS sphere data format",
    "- in.confined_spheres.lammps: first-pass runnable LAMMPS input",
    "",
    `Active particles: ${activeCount}`,
    `Confinement shape: ${cell.confinementShape}`,
    `Driving forces: ${state.forces.length}`,
    `Timestep: ${runtime.timestep}`,
    `Run steps: ${runtime.runSteps}`,
    `Simulated time: ${runtime.timestep * runtime.runSteps}`,
    `Dump interval: ${runtime.dumpEvery}`,
    `Thermo interval: ${runtime.thermoEvery}`,
    "",
    "Run with one of:",
    "lmp -in in.confined_spheres.lammps",
    "lammps -in in.confined_spheres.lammps",
    "",
    "Current limitation:",
    cell.confinementShape === "hexagon"
      ? "Hex confinement is emitted as six independent inward-facing harmonic plane walls."
      : "Square confinement is emitted as reflective center-walls one particle radius inside the LAMMPS wrapper.",
    "",
  ].join("\n");
}

function generateConfinementWall(state, cell) {
  if (cell.confinementShape === "hexagon") {
    return generateHexRegionWall(state, cell);
  }

  return [
    `variable particle_radius equal ${fmt(RADIUS)}`,
    "variable wall_xlo equal xlo+v_particle_radius",
    "variable wall_xhi equal xhi-v_particle_radius",
    "variable wall_ylo equal ylo+v_particle_radius",
    "variable wall_yhi equal yhi-v_particle_radius",
    "fix wrapper all wall/reflect xlo ${wall_xlo} xhi ${wall_xhi} ylo ${wall_ylo} yhi ${wall_yhi}",
  ];
}

function generateHexRegionWall(state, cell) {
  const planes = centerAccessiblePlanes(cell.confinementBoundary, RADIUS);
  const cutoff = Math.max(state.tightness, 0.001);
  return [
    "# Hex wall: six independent inward-facing plane walls define the center-accessible particle region.",
    ...planes.map((plane, index) =>
      `region hex_side_${index + 1} plane ${fmt(plane.point.x)} ${fmt(plane.point.y)} 0.0 ${fmt(plane.normal.x)} ${fmt(plane.normal.y)} 0.0 side in units box`
    ),
    ...planes.map((_, index) =>
      `fix hexwall_${index + 1} all wall/region hex_side_${index + 1} harmonic 100.0 0.0 ${fmt(cutoff)}`
    ),
  ];
}

function centerAccessiblePlanes(vertices, particleRadius) {
  return vertices.map((start, index) => {
    const end = vertices[(index + 1) % vertices.length];
    const dx = end.x - start.x;
    const dy = end.y - start.y;
    const length = Math.hypot(dx, dy);
    const inward = {
      x: -dy / length,
      y: dx / length,
    };
    return {
      point: {
        x: start.x + inward.x * particleRadius,
        y: start.y + inward.y * particleRadius,
      },
      normal: inward,
    };
  });
}

function generateForceVariables(state) {
  const forces = state.forces.map(forceToConfig);
  if (forces.length === 0) {
    return [
      "variable fdrive_x equal 0.0",
      "variable fdrive_y equal 0.0",
    ];
  }

  const lines = [];
  const fxTerms = [];
  const fyTerms = [];
  forces.forEach((force, index) => {
    const n = index + 1;
    const theta0 = force.direction_degrees * Math.PI / 180;
    const phase = force.phase_degrees * Math.PI / 180;
    const omega = force.rotation_rate_degrees_per_time * Math.PI / 180;
    lines.push(`variable f${n}_theta equal ${fmt(theta0)}+${fmt(omega)}*time`);
    lines.push(`variable f${n}_mag equal ${fmt(force.amplitude)}*sin(2.0*${PI}*${fmt(force.frequency)}*time+${fmt(phase)})`);
    lines.push(`variable f${n}_x equal v_f${n}_mag*cos(v_f${n}_theta)`);
    lines.push(`variable f${n}_y equal v_f${n}_mag*sin(v_f${n}_theta)`);
    fxTerms.push(`v_f${n}_x`);
    fyTerms.push(`v_f${n}_y`);
  });
  lines.push(`variable fdrive_x equal ${fxTerms.join("+")}`);
  lines.push(`variable fdrive_y equal ${fyTerms.join("+")}`);
  return lines;
}

function lammpsDomainExtents(cell) {
  const xs = cell.lammpsDomain.map((point) => point.x);
  const ys = cell.lammpsDomain.map((point) => point.y);
  return {
    xlo: Math.min(...xs),
    xhi: Math.max(...xs),
    ylo: Math.min(...ys),
    yhi: Math.max(...ys),
  };
}

function fmt(value) {
  return Number(value).toFixed(8);
}
